FROM mysql:8.0

ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD


COPY ./initDB.sql /docker-entrypoint-initdb.d/

CMD ["mysql", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD", "$MYSQL_DATABASE", "<", "/docker-entrypoint-initdb.d/initDB.sql"]
