# fly.toml file generated for le-quai-antique-db on 2023-03-16T21:25:34+01:00

app = "le-quai-antique-db"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"

[mounts]
  source = "mysqldata"
  destination = "/var/lib/mysql"

[env]
  MYSQL_DATABASE = "le-quai-antique-db"
  MYSQL_USER = "hh9acw196zjemkldeebe"

[experimental]
  cmd = ["--default-authentication-plugin", "mysql_native_password", "--datadir", "/var/lib/mysql", "--performance-schema=OFF", "--innodb-buffer-pool-size", "64M"]

